// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var discount = 0.05;

var total = 7 * 14.50;

var afterDiscount = total * (1.0 - discount);

console.log("Price before discount: $", total);

console.log("Price after discount: $", afterDiscount);

console.log("Prix avant réduction: " + (String(total) + " €"));

console.log("Prix après réduction: " + (String(afterDiscount) + " €"));

var result = Math.sqrt(Math.abs(-3.75));

console.log("The sqrt is ", result);

var area = Math.PI * 7.0 * 7.0;

console.log("The area is ", area);

var poem = "The boy stood on the burning deck, Whence all but he had fled;\nThe flames that lit the battle’s wreck...";

console.log(poem);

var wind_chill = 13.12 + 0.6215 * 5.0 - 11.37 * Math.pow(20.0, 0.16) + 0.3965 * 5.0 * Math.pow(20.0, 0.16);

console.log("At temperature " + (String(5.0) + (" degrees C and wind speed " + (String(20.0) + (",\n          the wind chill temperature is " + (String(wind_chill) + ""))))));

var qty = 7;

var price = 14.50;

var r = 7.0;

var temp = 5.0;

var wind_speed = 20.0;

exports.qty = qty;
exports.price = price;
exports.discount = discount;
exports.total = total;
exports.afterDiscount = afterDiscount;
exports.result = result;
exports.r = r;
exports.area = area;
exports.poem = poem;
exports.temp = temp;
exports.wind_speed = wind_speed;
exports.wind_chill = wind_chill;
/*  Not a pure module */
